### ISSUE TITLE
你希望Whu Lambda.moe实现哪些功能？

### ISSUE THREAD

**Issue by minnakamiyuki** [Whu-Lambda/whu-lambda-moe#1]
希望能听到大家的反馈，我们会渐进式地实现大家想要的功能！

**Comment by Geno1024** [comment]
1. 展示团队及成员
2. 知识分享（文章）
3. 分享会会议记录 [1]

[1]: Chen, G. (2022). Chat in WHU-Lambda Web Group. _QQ_, 2022(1), 11.

**Comment by Geno1024** [comment]
买个域名

**Comment by xiayulu** [comment]
1. 活动管理：讨论预约，分享安排
2. 内容管理：相关文章发布
